### ISSUE TITLE
Unable to set the style for Tabablzcontrol in App.xaml !

### ISSUE THREAD

**Issue by kushwb** [kushwb/DragablzIssue#2]
Trying to add this but its unable to find the style,
<Style TargetType="{x:Type dragablz:TabablzControl}" BasedOn="{StaticResource MaterialDesignTabablzControlStyle}" />

**Comment by Keboo** [comment]
@kushwb you need to add the material design resource dictionary included with the dragablz library.

Put this in your App.xaml
```XML
<!-- Dragablz Material Design -->
<ResourceDictionary Source="pack://application:,,,/Dragablz;component/Themes/materialdesign.xaml"/>
```

You can see an example of how to setup the app.xaml [here](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/master/MahMaterialDragablzMashUp/App.xaml)

**Comment by kushwb** [comment]
Thanks ! Damn what the hell was i thinking.. Added the same in the repo ! Did you get time to see the other issues over here ?

**Comment by kushwb** [comment]
Updated repo with required changes to fix this in app.xaml file.
